Adding Header and Headline section features
npydi/Portfolio pull request #1
Opened 2022-09-23 21:40 UTC by npydi

This PR contains:
Header and Headline sections

2022-09-23 22:46 UTC, jerryowusu requested changes
Hi @npydi :wave: 

Good job so far!
However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![soclose](https://user-images.githubusercontent.com/65233860/192066144-1c312555-6ef3-4e41-8761-5b5ad5f3f454.gif)


## Highlights
:heavy_check_mark: well organised files
:heavy_check_mark: good commit messages

## Required Changes ♻️

- [ ]  You must update your readme to reflect all the header and sections on this template. Remember, a good and proffessional readme is a requirement for the approval of this project.


_Check the comments under the review._

## Optional suggestions

- [ ]  I see that the lighthouse linter is failing. I check and everything is working on my pc and I believe it is a global issue, that is why I am able to review this project. Kindly check and make sure all linters are passing as soon as you can.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 22:46 UTC, jerryowusu commented on index.html
> +	</body>
To make your code more readable and proffessional, kindly use not more than two spaces (2 spacebar clicks) for indentation.

2022-09-23 22:46 UTC, jerryowusu commented on index.html
> +				<span class="myLogo">My Logo</span>
The logo is a link that always navigates to the home page. Kindly use an `a` tag instead of a `span` for it. This will help your code to be up to standard since that is a good convention. It is also good for semantics and good user experience.

2022-09-24 00:01 UTC, npydi commented on index.html
> +	</body>
Thank you @jerryowusu for reviewing the code. sorry about missing the readme file.
Both pending tasks are done. 
  - Included readme file
  - All linter checks have passed.

2022-09-24 11:58 UTC, sajid-munawar requested changes
Hi @topeogunleye, 

_Great job so far 👏 💯 👍. You've done well implementing some of the requested changes. However, there are still some which aren't addressed yet. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 
  - Addressed some of the issues raised from the previous review. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
  
  - N/A 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-24 11:58 UTC, sajid-munawar commented on index.html
> +					<p class="connect">LET'S CONNECT</p>
- [ ] The button is a link `a` or` button` tag, and follow the button styling: Active, Hover and Pressed (see design).

* Apart from being semantically correct, the` a` tag will let you connect to other sections of the website, using href.

2022-09-24 11:58 UTC, sajid-munawar commented on index.html
> +					</ul>
- [ ] It is very nice you wrapped your social media's icon with a` ul` and `li` list but please add your social media icons inside an `a` tag. Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2022-09-24 12:49 UTC, npydi commented on index.html
> +					<p class="connect">LET'S CONNECT</p>
@sajid-munawar Hi Sajid, I am here regarding your review, could you please clarify more on the 'button'? exactly which element needs to be a button?
(as far as I see according to the template there were no buttons in the part of my project)

2022-09-24 12:51 UTC, npydi commented on index.html
> +					</ul>
It's done.

2022-09-24 13:19 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @npydi  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:

## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 13:19 UTC, Nyame-Wolf commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/nia-npydi7234)
[OPTIONAL]Kindly add your username and a link to your github account as well as the twitter and linkedin by replacing the above as follows
`GitHub: [@npydi](https://github.com/npydi)`
`- Twitter: [@NiaPydi](https://twitter.com/NiaPydi)`

This makes your page look more professional since I

2022-09-24 13:19 UTC, Nyame-Wolf commented on README.md
> +Feel free to check the [issues page](../../issues/).
[OPTIONAL] Please add the issues page to this project here. replace the `(../../issues/)` with a link that opens your issues page `(https://...)`.
You can get this by opening issue on this repo and copying the link.

2022-09-24 13:19 UTC, Nyame-Wolf commented on README.md
> +This project is [MIT](./LICENSE) licensed.
[OPTIONAL]I recommend adding an MIT.md file as licence for all your projects. Details on how to are on the below link you have in your readme. [MIT license](https://choosealicense.com/licenses/mit/)

2022-09-24 13:19 UTC, Nyame-Wolf commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
[OPTIONAL]This is the link with instructions on how to add a licence. It does not need to appear on your readme

2022-09-24 13:19 UTC, Nyame-Wolf commented on index.html
> +		  <p class="connect">LET'S CONNECT</p>
[OPTIONAL] Please note that this is a heading. Kindly add a `<hx>` that is `<h2>` to `<h6>` for semantic purpose as well to satisfy screen readers.

2022-09-24 13:58 UTC, merged

2022-09-24 15:05 UTC, sajid-munawar commented on index.html
> +					<p class="connect">LET'S CONNECT</p>
@npydi  `let's connect` is a button where you want to connect with other sections of your project.